import "../styles/globals.css";
import { JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "@/components/nav";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/themes";

const jetbrainsMono = JetBrains_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodeLobby",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        signIn: {
          baseTheme: neobrutalism,
          variables: {
            colorPrimary: "blue",
            colorText: "white",
          },
        },
        signUp: {
          baseTheme: neobrutalism,
          variables: {
            colorPrimary: "blue",
            colorText: "white",
          },
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={jetbrainsMono.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Nav />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
